# Generated by Django 4.1.1 on 2022-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_un", models.CharField(max_length=200)),
                (
                    "product_description",
                    models.DateTimeField(verbose_name="description"),
                ),
                ("product_class", models.CharField(max_length=200)),
                ("product_group", models.CharField(max_length=200)),
                ("product_provisions", models.CharField(max_length=200)),
                ("product_paragraph", models.CharField(max_length=200)),
                ("product_name", models.CharField(max_length=200)),
                ("product_caution", models.CharField(max_length=200)),
                ("product_warning", models.CharField(max_length=200)),
            ],
        ),
    ]
