# Generated by Django 4.1.1 on 2022-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HazClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("haz_num", models.CharField(max_length=200)),
                ("haz_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_un", models.CharField(max_length=200)),
                ("product_psn", models.CharField(max_length=200)),
                ("product_haz_class", models.CharField(max_length=200)),
                ("product_sub_class", models.CharField(max_length=200)),
                ("product_pg", models.CharField(max_length=200)),
                ("product_sp", models.CharField(max_length=200)),
                ("product_paragraph", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sp_code", models.CharField(max_length=200)),
                ("sp_desc", models.CharField(max_length=200)),
            ],
        ),
    ]
