# Generated by Django 4.1.1 on 2022-10-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(max_length=200),
        ),
    ]
