# Generated by Django 4.1.1 on 2022-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spcode", name="desc", field=models.CharField(max_length=3000),
        ),
    ]
