# Generated by Django 4.1.1 on 2022-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_alter_spcode_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazclass", name="desc", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="spcode", name="desc", field=models.TextField(),
        ),
    ]
