# Generated by Django 4.1.1 on 2022-11-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_rename_product_caution_product_product_haz_class_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HazClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("haz_num", models.CharField(max_length=200)),
                ("haz_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sp_code", models.CharField(max_length=200)),
                ("sp_desc", models.CharField(max_length=200)),
            ],
        ),
    ]
