# Generated by Django 4.1.1 on 2022-11-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_hazsubstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazclass',
            name='haz_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazclass',
            name='haz_num',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
