# Generated by Django 4.1.1 on 2022-11-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_hazclass_haz_name_hazclass_haz_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazclass',
            name='haz_name',
        ),
        migrations.RemoveField(
            model_name='hazclass',
            name='haz_num',
        ),
    ]
